language: python
python:
- '2.7'
- '3.6'
script:
- pip install persist-queue
- python setup.py sdist
- python setup.py test
- django_tests/all_tests.sh
deploy:
  provider: pypi
  user: AppInsightsSDK
  password:
    secure: YisLTEfN9qhQzVg0FN2YJCl6dZ/3BsaW2/uzlP5St3sOJwEipOI3mUElvKrd58cha/L0qtWXxh9M3szJ3NT3DEx2K5Rysl/4yOWJPQ2/1P+dOyOXYPTm8RcJldSm2S65qjs2eWZrnyYTnj30ww8pbOuIZeI+U7RGDULGg0+0R9U=
  distributions: "sdist bdist_wheel"
  on:
    tags: true
    repo: Microsoft/ApplicationInsights-Python
