language: python
python:
- '2.7'
- '3.4'
script:
- python setup.py sdist
- python setup.py test
- django_tests/all_tests.sh
deploy:
  provider: pypi
  user: BogdanBe
  password:
    secure: Vy3FxFJuBkkZzqozmdT7l3eMNRvGfuDXXlBy3mCfiO3XP7eYId/MJ2ftnkEqYrNoObJlWTQ3vIQpZaO/lE6KIaHO5uT1T+9Fv7E2FLIoJ0+JOV+dy219LfpARojOA5Mf+tQyGffqUyQ2zFkYnFQ/Mo1Av7wPLKGzncbUmwbrGoE=
  distributions: "sdist bdist_wheel"
  on:
    tags: true
    repo: Microsoft/AppInsights-Python
